name : www.dianafayelee.com
brand : Diana Faye Lee
description : Death Metal Dev
keyword : 
url : http://www.dianafayelee.com
email : dianafaye17@gmail.com
github : dianafaye17
linkedin : dianafayelee
author : Diana Lee
year : 2015
markdown : kramdown
exclude :
  - node_modules
